name: Autograding Tests
'on': 
  - push
  - workflow_dispatch
  - repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up JDK 22
      uses: actions/setup-java@v2
      with:
        java-version: '22'
        distribution: 'adopt'
    - name: Java Variables
      id: java-variables
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Java Variables
        setup-command: ''
        command: mvn test
        timeout: 10
        max-score: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        JAVA-VARIABLES_RESULTS: "${{steps.java-variables.outputs.result}}"
      with:
        runners: java-variables
